#Introducci√≥n a Microservicios: Arquitectura y Contenedores
services:
  app:
    container_name: monolito-ui
    build: ./monolito
    ports:
      - "8080:80"
    volumes:
      - ./monolito/src:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=ecommerce
      - DB_USER=user
      - DB_PASS=password
    depends_on:
      - db

  db:
    container_name: monolito-db
    image: mysql:8.0
    restart: always
    #platform: linux/amd64 descomentar si se ejecuta en M1/M2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./monolito/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  
  notifications:
    container_name: notifications
    build: ./notification-service
    ports:
      - "5000:8080"
