#Introducci√≥n a Microservicios: Arquitectura y Contenedores
services:
  app:
    container_name: monolito-ui
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=ecommerce
      - DB_USER=user
      - DB_PASS=password
    depends_on:
      - db

  db:
    container_name: monolito-db
    image: mysql:5.7
    #platform: linux/amd64 descomentar si se ejecuta en M1/M2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
