apiVersion: v1
kind: Secret
metadata:
  name: mysql-passwords
  namespace: default # namespace por defecto, cambiar si se usa otro. Si no lo especificas, se crear√° en el namespace por defecto.
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: ecommerce
  MYSQL_USER: user
  MYSQL_PASSWORD: password
