apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: ecommerce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: monolito-ui
        image: monolito:v3 
        imagePullPolicy: Never #si la imagen es local, de lo contrario, elimina esta l√≠nea
        env:
        - name: DB_HOST
          value: "mysql-service" # Nombre del servicio de MySQL
        - name: DB_NAME
          value: "ecommerce"
        - name: DB_USER
          value: "user"
        - name: DB_PASS
          value: "password"
        ports:
        - containerPort: 80